### ISSUE TITLE
go 1.12+

### ISSUE THREAD

**Issue by pedromorgan** [daaku/go.zipexe#4]
so this is causing a problem as go 1.11 is not supported.. What makes it required 1.2 ??

**Comment by daaku** [comment]
Can you elaborate on what makes it require 1.2 or provide some context around why 1.11 is not supported?

**Comment by pedromorgan** [comment]
Its a part of "go.rice https://github.com/GeertJohan/go.rice

What is being using on the https://github.com/ts2/ts2-sim-server (module based)

the tests for 1.11 are failing - https://travis-ci.org/ts2/ts2-sim-server/builds/529260900

**Comment by daaku** [comment]
Got it, the context help. Reduced the requirement to go 1.11 in `v1.0.1`.
